<?php

namespace Nemundo\Workflow\App\Workflow\Com\Breadcrumb;


use Nemundo\Package\Bootstrap\Breadcrumb\BootstrapBreadcrumb;
use Nemundo\Workflow\App\Workflow\Site\WorkflowSite;

class WorkflowBreadcrumb extends BootstrapBreadcrumb
{


    protected function loadCom()
    {
        parent::loadCom(); // TODO: Change the autogenerated stub

        $this->addSite(WorkflowSite::$site);

    }

    public function getHtml()
    {
        return parent::getHtml(); // TODO: Change the autogenerated stub
    }

}