<?php

namespace Nemundo\Workflow\App\Workflow\Com\Breadcrumb;


use Nemundo\Package\Bootstrap\Breadcrumb\BootstrapBreadcrumb;
use Nemundo\Workflow\App\Workflow\Site\WorkflowSite;

class WorkflowBreadcrumb extends BootstrapBreadcrumb
{


    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub

        $this->addSite(WorkflowSite::$site);

    }

    public function getContent()
    {
        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}