<?php

namespace Nemundo\Workflow\App\Notification\Com\Table;


use Nemundo\Package\Bootstrap\Table\BootstrapTable;

class NotificationTable extends BootstrapTable
{

    public function getContent()
    {


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}