<?php

namespace Nemundo\Workflow\App\Search\Com;


use Nemundo\Html\Form\Select\Option;
use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;
use Nemundo\Workflow\App\Search\RedefineSearchList;

class RedefineSearchListBox extends BootstrapListBox
{


    /**
     * @var RedefineSearchList
     */
    public $redefineSearchList;


    protected function loadContainer()
    {
        parent::loadContainer();
        $this->redefineSearchList = new RedefineSearchList();

        //$this->submitOnChange = true;


    }

    public function getHtml()
    {

        $this->multiSelect = true;

        $this->value = $this->getValue();

        foreach ($this->redefineSearchList->getItemList() as $redefineItem) {


            $option = new Option();
            $option->value = $redefineItem->id;
            $option->label = $redefineItem->label . ' (' . $redefineItem->count . ')';
            if ($redefineItem->count == 0) {
                //$option->disabled = true;
            }

            $this->addOption($option);


        }


        return parent::getHtml(); // TODO: Change the autogenerated stub

    }


}