<?php

namespace Nemundo\Workflow\App\ContentTemplate\Type\Comment;


use Nemundo\App\Content\Type\Workflow\AbstractWorkflowStatus;
use Nemundo\Core\Debug\Debug;
use Nemundo\Core\Type\Text\Html;
use Nemundo\Db\DbConfig;
use Nemundo\Workflow\App\ContentTemplate\Data\Comment\Comment;
use Nemundo\Workflow\App\ContentTemplate\Data\Comment\CommentReader;
use Nemundo\Workflow\App\ContentTemplate\Data\Comment\CommentUpdate;
use Nemundo\Workflow\App\SearchEngine\Builder\SearchEngineBuilder;


class CommentType extends AbstractWorkflowStatus
{

    /**
     * @var string
     */
    public $comment;


    // commentLabel

    protected function loadData()
    {
        $this->contentName = 'Kommentar';
        $this->contentId = '3d7012e5-6751-4d49-8d68-a0f49a888718';
        $this->formClass = CommentTypeForm::class;
        $this->viewClass = CommentView::class;
        $this->subject = 'Es wurde was kommentiert';


        $this->changeStatus = false;

        if ($this->dataId !== null) {

            $row = (new CommentReader())->getRowById($this->dataId);
            $this->comment = (new Html($row->comment))->getValue();

        }


    }

    public function saveType()
    {

        if ($this->dataId == null) {

            $data = new Comment();
            $data->comment = $this->comment;
            $this->dataId = $data->save();

            $this->saveContentLog();


            $builder = new SearchEngineBuilder();
            $builder->contentType = $this;
            $builder->addText($this->comment);




        } else {

            $update = new CommentUpdate();
            $update->comment = $this->comment;
            $update->updateById($this->dataId);

        }

    }


    public function getSubject()
    {


        return parent::getSubject(); // TODO: Change the autogenerated stub
    }


}