<?php

namespace Nemundo\Workflow\App\ContentTemplate\Type\Comment;


use Nemundo\App\Content\Type\AbstractTreeContentType;
use Nemundo\Core\Type\Text\Html;
use Nemundo\Workflow\App\ContentTemplate\Data\Comment\Comment;
use Nemundo\Workflow\App\ContentTemplate\Data\Comment\CommentReader;
use Nemundo\Workflow\App\Workflow\Content\Type\AbstractWorkflowStatus;

class CommentType extends \Nemundo\App\Content\Type\Workflow\AbstractWorkflowStatus  // AbstractWorkflowStatus  // AbstractTreeContentType
{

    /**
     * @var string
     */
    public $comment;

    protected function loadData()
    {
        $this->objectName = 'Kommentar';
        $this->objectId = '3d7012e5-6751-4d49-8d68-a0f49a888718';
        $this->formClass = CommentTypeForm::class;
        $this->itemClass = CommentItem::class;
        $this->subject = 'Es wurde was kommentiert';


        if ($this->dataId !== null) {

            $row = (new CommentReader())->getRowById($this->dataId);
            $this->comment = (new Html($row->comment))->getValue();

        }


    }

    public function saveItem()
    {

        $data = new Comment();
        $data->comment = $this->comment;
        $this->dataId = $data->save();

        $this->saveContentLog();

    }


    public function getSubject()
    {


        return parent::getSubject(); // TODO: Change the autogenerated stub
    }


}