<?php

namespace Nemundo\Workflow\App\ContentTemplate\Type\Comment;


use Nemundo\App\Content\View\AbstractContentView;
use Nemundo\Com\Html\Basic\Paragraph;

class CommentView extends AbstractContentView
{

    public function getHtml()
    {

        $type = new CommentType($this->dataId);

        $p = new Paragraph($this);
        $p->content = $type->comment;


        return parent::getHtml(); // TODO: Change the autogenerated stub
    }

}